version: "2"
run:
  timeout: 5m
  tests: true

linters:
  enable:
    - govet
    - staticcheck
    - revive
    - errcheck
    - ineffassign
    - unused
    - misspell
    - gocyclo
    - gocritic
  disable:
    - lll


