run:
  timeout: 5m
  tests: true
  skip-dirs:
    - ent

linters:
  enable:
    - govet
    - staticcheck
    - gofmt
    - goimports
    - revive
    - errcheck
    - ineffassign
    - unused
    - misspell
    - gocyclo
    - gocritic
  disable:
    - lll

linters-settings:
  gocyclo:
    min-complexity: 18
  revive:
    rules:
      - name: indent-error-flow
      - name: exported
        severity: warning
      - name: errorf
      - name: unreachable-code
  misspell:
    locale: US

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - gocritic
        - revive

