version: '3'

tasks:
  tidy:
    cmds:
      - go mod tidy

  gen:
    deps: [tidy]
    cmds:
      - go generate ./...

  run:
    deps: [gen]
    cmds:
      - go run ./cmd/server

  build:
    deps: [gen]
    cmds:
      - go build -o bin/server ./cmd/server

  restart:
    deps: [build]
    cmds:
      - bash scripts/run.sh

  dev:
    deps: [gen]
    cmds:
      - air -c .air.toml

  up:
    cmds:
      - docker compose up -d

  down:
    cmds:
      - docker compose down -v
