// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AnonymousUser is the predicate function for anonymoususer builders.
type AnonymousUser func(*sql.Selector)

// ConfigHistory is the predicate function for confighistory builders.
type ConfigHistory func(*sql.Selector)

// ExportRecord is the predicate function for exportrecord builders.
type ExportRecord func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// UserAuth is the predicate function for userauth builders.
type UserAuth func(*sql.Selector)

// UserConfig is the predicate function for userconfig builders.
type UserConfig func(*sql.Selector)
